"""
Constants - Magic numbers and configuration values
"""
# Rate limiting delays (seconds)
RATE_LIMIT_DELAY = 0.2
RATE_LIMIT_DELAY_MEDIUM = 0.3
RATE_LIMIT_DELAY_LONG = 0.5
RATE_LIMIT_DELAY_VERY_LONG = 1.0

# Volume analysis thresholds
VOLUME_UNUSUAL_THRESHOLD = 2.0  # 2x average volume = unusual activity

# Default periods
DEFAULT_PERIOD = '1y'
DEFAULT_HISTORY_DAYS = 30

# Technical indicators
RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70
MACD_SIGNAL_PERIOD = 9
BOLLINGER_PERIOD = 20
BOLLINGER_STD = 2

# Financial thresholds
CURRENT_RATIO_GOOD = 2.0
CURRENT_RATIO_ACCEPTABLE = 1.5
CURRENT_RATIO_MINIMUM = 1.0
QUICK_RATIO_GOOD = 1.5
QUICK_RATIO_ACCEPTABLE = 1.0
DEBT_TO_EQUITY_EXCELLENT = 0.3
DEBT_TO_EQUITY_GOOD = 0.5
DEBT_TO_EQUITY_ACCEPTABLE = 1.0
DEBT_TO_EQUITY_HIGH = 2.0

# News sentiment thresholds
SENTIMENT_POSITIVE_THRESHOLD = 0.05
SENTIMENT_NEGATIVE_THRESHOLD = -0.05
NEWS_IMPACT_HIGH_THRESHOLD = 0.3

# ML model cache
MODEL_CACHE_VERSION = 8

# API timeouts
FINVIZ_TIMEOUT = 10
YFINANCE_TIMEOUT = 15
SEC_API_TIMEOUT = 15

# Data limits
MAX_NEWS_ITEMS = 10
MAX_PEER_COMPARISON = 5
MAX_SCREENER_RESULTS = 100




